name: Kootenay Mercantile
favicon: null
layout_spectrum: 0.584340822417289
typography_spectrum: 0.13513
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#441205'
    - '#ffffff'
    - '#2c5d7a'
    - '#ca9767'
    - '#77442a'
  brandStrength: 0
  lightness: 0.09632810391485691
  saturation: 0.5385338112246245
  rhythmicContrast: 0.6943080560304224
purpose: []
