name: Kootenay Mercantile
favicon: null
layout_spectrum: 0.584340822417289
typography_spectrum: 0.6925095543265343
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.023793779779225588
  lightness: 0.09632810391485691
  saturation: 0.5385338112246245
  rhythmicContrast: 0.6943080560304224
purpose: []
